"""challenge32

Revision ID: 13dbf7e49de4
Revises: e1af6d30953d
Create Date: 2020-06-17 15:31:10.107865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13dbf7e49de4'
down_revision = 'e1af6d30953d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('livename', sa.String(length=128), nullable=True),
    sa.Column('live_url', sa.String(length=256), nullable=True),
    sa.Column('liveuser_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liveuser_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_livename'), 'live', ['livename'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_livename'), table_name='live')
    op.drop_table('live')
    # ### end Alembic commands ###
